[UI] fix frontend metric & config selection bugs + refactor
amosproj/amos2024ws03-android-zero-instrumentation pull request #134
Opened 2024-12-02 18:17 UTC by luca-dot-sh

This PR refactors most of the frontend and fixes bugs.

Bugfixes:
- configurations being wrongly shared amogst PIDs
- metric selection only displaying global
- submit button being displayed if there are no changes
- filtering is now being applied corrently for both filter and metric options, depending on what is actually configured
- switch mode button is only shown if there is data being displayed.

Refactorings:
- ConfigurationManager now tracks local (unconfirmed selection) and backend (actual active options) config and can be "synced" via submitting a config.
- DataStreamManager now uses SharedFlow to prevent multiple subscriptions
- Applications and Processes are provided by a combined component called RunningComponentProvider and Application Info is cached now
- VisualizationScreen now gets its state via a single data class
- VisualizationViewModel now does less copying but instead derives its information in a combined flow from the selected options, but still needs some improvements
- some renamings

2024-12-03 01:52 UTC, fhilgers commented
- [ ] TODO: fix visualization screen

2024-12-03 01:52 UTC, fhilgers requested changes
- [ ] Fix visualization screen

2024-12-03 11:56 UTC, luca-dot-sh commented
The visualization should work now :)

2024-12-03 12:03 UTC, fhilgers commented
Great, I'll check it out this afternoon!

2024-12-03 14:24 UTC, fhilgers commented
I cannot confirm, either the event does not show at all, or it is only displayed very briefly:

[Screencast From 2024-12-03 15-22-47.webm](https://github.com/user-attachments/assets/f47d22dd-958f-4981-8327-24d98e0cbfb7)

2024-12-03 17:06 UTC, luca-dot-sh commented
Weird, i will check it out again later this evening or tomorrow morning

2024-12-03 23:55 UTC, luca-dot-sh commented
We were using a Flow instead of a StateFlow that wrongfully updated every second, leading to flickering. This was not present in the mocked version as its process list is constant.

2024-12-03 23:56 UTC, luca-dot-sh commented on frontend/app/src/main/java/de/amosproj3/ziofa/ui/visualization/VisualizationViewModel.kt
> +            .stateIn(viewModelScope, SharingStarted.Lazily, DEFAULT_SELECTION_DATA)
This is the important change.

2024-12-04 01:55 UTC, fhilgers approved these changes

2024-12-04 01:55 UTC, merged