Features refactor
amosproj/amos2024ws03-android-zero-instrumentation pull request #150
Opened 2024-12-09 17:20 UTC by ffranzgitHub

Closes #124

2024-12-09 18:20 UTC, Mr-Kanister commented
I believe the merge screwed things up a lot, I tried doing it myself again, but I don't know exactly how things are supposed to be according to you. Please do it once more.

2024-12-10 12:16 UTC, fhilgers commented
If you need help, let me know, I can look into it and fix the missing stuff.

2024-12-10 15:40 UTC, Mr-Kanister requested changes

2024-12-10 15:40 UTC, Mr-Kanister commented on rust/backend/daemon/src/features.rs
> +    pub fn _apply_all_features(&mut self, ebpf: &mut Ebpf, config: &mut Configuration) -> Result<(), EbpfError> {
I believe this can be removed in favour of `update_from_config()` below

2024-12-10 16:02 UTC, Mr-Kanister approved these changes

2024-12-10 17:19 UTC, merged